services:
  - type: web
    name: productivity-tips-strapi
    env: node
    plan: free
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/mehulchopda/strapiconf2022-workshop-strapi
    branch: main
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi
    plan: free # This database will expire 90 days after creation
